version: 2

build:
   os: ubuntu-20.04
   tools:
     python: "3.10"
     apt_packages:
       - dvipng
       - texlive-latex-extra

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
