=pod

=head1 NAME

    Bio::EnsEMBL::Hive::DBSQL::JobMessageAdaptor

=head1 SYNOPSIS

    $dba->get_JobMessageAdaptor->register_message($job_id, $msg, $is_error);

=head1 DESCRIPTION

    This is currently an "objectless" adaptor that helps to store either warning-messages or die-messages generated by jobs

=head1 CONTACT

    Please contact ehive-users@ebi.ac.uk mailing list with questions/suggestions.

=cut


package Bio::EnsEMBL::Hive::DBSQL::JobMessageAdaptor;

use strict;

use base ('Bio::EnsEMBL::Hive::DBSQL::NakedTableAdaptor');


sub default_table_name {
    return 'job_message';
}


sub register_message {
    my ($self, $job_id, $msg, $is_error) = @_;

    chomp $msg;   # we don't want that last "\n" in the database

    my $table_name = $self->table_name();

        # (the timestamp 'time' column will be set automatically)
    my $sql = qq{
        REPLACE INTO $table_name (job_id, worker_id, retry, status, msg, is_error)
                           SELECT job_id, worker_id, retry_count, status, ?, ?
                             FROM job WHERE job_id=?
    };

    my $sth = $self->prepare( $sql );
    $sth->execute( $msg, $is_error, $job_id );
    $sth->finish();
}

1;

