#!/bin/bash

received="$*"
expected="$EHIVE_EXPECTED_BSUB"

if [ "$received" = "$expected" ];
then
    echo "Job <12345> is submitted to queue <abcde>"
    exit 0
else
    echo "diff: received $received"
    echo "diff: was expecting $expected"
    exit 1
fi

