package Hive::Test::FastaFactory;

use strict;
use warnings;

use lib 't/lib/';

use Hive::Test qw{spurt};

use base qw{Hive::Config};

sub test_suite_init {
    my $fasta = shift;
    ## write some sequences
    spurt <<EOF, $fasta;
>sequence1
ATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTA
GCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGAT
CTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTG
AGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTT
ATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTA
GCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGAT
CTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTG
AGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTT
ATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTA
GCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGAT
CTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTT
>sequence2
AGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCG
ATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTA
GTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGA
CGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTC
AGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCG
ATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTA
GTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGA
CGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTC
AGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCG
ATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTA
GTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGA
CGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTC
AGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCG
ATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTA
GTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGA
CGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTC
AGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCG
ATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTA
GTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGA
CGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTC
AGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCG
ATCGTACTGACTACTGAGTC
>sequence3
ATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTA
GCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGAT
CTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTG
AGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTT
ATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTA
GCTAGTCGGTGTGTGTGTTTAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTA
GTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGA
CGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTC
AGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCG
ATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTA
GTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGA
CGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTC
AGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCG
ATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTA
GTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGA
CGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTC
AGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCG
ATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTA
GTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGA
CGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTC
AGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCG
ATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGACGATCTAGCAGCTGTAGCTA
GTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTCAGTCGTACGTAGCGATCTGA
CGATCTAGCAGCTGTAGCTAGTCGGTGTGTGTGTTTATCGATCGTACTGACTACTGAGTC
EOF

   return (
       '-inputfile'        => $fasta,
       '-max_chunk_length' => 1,
       '-chunks_dir'       => '.',
       '-output_suffix'    => '.fa',
   );
}

sub pipeline_analyses {
    my $self = shift;
    return [
	{
	    -logic_name => 'fasta_factory',
            -module     => 'Bio::EnsEMBL::Hive::RunnableDB::FastaFactory',
            -input_ids => [ 
		 {
		     'inputfile'         => $self->o('inputfile'),
		     'max_chunk_length'  => 20000,
		     'output_prefix'     => $self->o('chunks_dir').'/test-1_',
		     'output_suffix'     => $self->o('output_suffix'),
		 },
		 {
		     'inputfile'         => $self->o('inputfile'),
		     'max_chunk_length'  => 200,
		     'output_prefix'     => $self->o('chunks_dir').'/test-2_',
		     'output_suffix'     => $self->o('output_suffix'),
		 } 

		],
	}
	];
}

package main;

use Test::More;
use Data::Dumper;
use File::Temp qw{tempdir};
use Hive::Apiarist;

BEGIN {
    use_ok( 'Bio::EnsEMBL::Hive::RunnableDB::FastaFactory' );
}
#########################

my $dir = tempdir CLEANUP => 1;
chdir $dir;

my @argv   = Hive::Test::FastaFactory::test_suite_init('input.fa');
my $config = Hive::Test::FastaFactory->init_pipeline_here( @argv );

my $apiarist = Hive::Apiarist->new();
my $job      = $apiarist->get_a_new_job( $config->pipeline_url, 1 );
ok( $job, 'got work to do' );

my $runnable = Bio::EnsEMBL::Hive::RunnableDB::FastaFactory->new();
ok($runnable, 'instantiation');

run_job( $runnable, $job );
##
## do some checks
##
my $expected_filename = 'test-1_1.fa';
ok(-e $expected_filename, 'output file exists');

is((stat($expected_filename))[7], (stat('input.fa'))[7], 'file size of input == output');

my @all_files = glob('test-1_*.fa');
is(@all_files, 1, 'exactly one output file');

## 
## next job
##
my $job      = $apiarist->get_a_new_job( $config->pipeline_url, 2 );
ok( $job, 'got more work to do' );

run_job( $runnable, $job );





sub run_job {
    my ($runnable, $job) = @_;
    $job->param_init( 
	$runnable->param_defaults(), 
	$job->input_id(),
	);
    $runnable->input_job( $job );    
    $runnable->fetch_input();
    $runnable->run();
    $runnable->write_output();
}

chdir $ENV{'EHIVE_ROOT_DIR'};

done_testing();
