#!/bin/bash

action=$1
module=$2
fd_in=$3
fd_out=$4
debug=$5

read -r -d '' usage << "EOF"
Usage:
        $0 compile module_name
        $0 run module_name fd_in fd_out debug
        $0 version
EOF

# change to java subdirectory
wrapper_dir=$(dirname "$0")
cd "$wrapper_dir"

if [ "$action" == "version" ]; then
	exec ant -S -q version
elif [ "$action" == "compile" ]; then
	if [[ -z "$module" ]]; then
		echo "Syntax error"
		echo "$usage"
		exit 1
	fi
	echo "compiling"
	exec ant "-Dorg.ensembl.hive.module=$module" compile_wrapper
elif [ "$action" == "run" ]; then
	CLASSPATH=$PWD/build:$CLASSPATH
	if [[ -z "$module" || -z "$fd_in" || -z "$fd_out" || -z "$debug" ]]; then
		echo "Syntax error"
		echo "$usage"
		exit 1
	fi
	echo "Running '$module $fd_in $fd_out' in $PWD"
	#java -cp "lib/*" org.ensembl.hive.Wrapper "$module" "$fd_in" "$fd_out" "$debug"
    ant -Dorg.ensembl.hive.module=$module -Dorg.ensembl.hive.pipe_in=$fd_in -Dorg.ensembl.hive.pipe_out=$fd_out -Dorg.ensembl.hive.debug=$debug run_wrapper
else
	echo "Command-line error: No mode provided"
	echo "$usage"
	exit 1
fi
